---
title: "Teaching"
editor: 
  markdown: 
    wrap: 72
---
## Instructor
  <table>
  <tr>
    <td><b>Math 252: Elementary Differential Equations </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Summer 2023</td>
  </tr>
    <tr>
    <td><b>Math 250: Introductory Linear Algebra</b></td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Summer 2025</td>
  </tr>
  </table>

## Teaching Assistant

<table>
  <tr>
    <td><b>Math 251: Multivariable Calculus </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Fall 2022</td>
  </tr>
  <tr>
    <td><b>Math 152: Calculus II for the Mathematical and Physical Sciences </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Spring 2023</td>
  </tr>
  <tr>
    <td><b>Math 151: Calculus I for the Mathematical and Physical Sciences </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Fall 2023</td>
  </tr>
  <tr>
    <td><b>Math 481: Mathematical Theory of Statistics (TA at large) </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Spring 2024</td>
  </tr>
  <tr>
    <td><b>Math 135: Calculus I for the Life and Social Sciences </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Fall 2024</td>
  </tr>
  <tr>
    <td><b>Math 252: Elementary Differential Equations (TA at large) </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Spring 2025</td>
  </tr>
  <tr>
    <td><b>Math 251: Multivariable Calculus </b> </td>
    <td> \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Fall 2025</td>
  </tr>
  </table>

## Mentor  

  <table>
      <tr>
        <td><b>Basic $\infty$-category theory </b> </td><td>\ \ \ \ Direct Reading Program</td><td> \ \ \ \ Rutgers University</td><td style="text-align: right;">\ \ \ Summer 2024</td>
      </tr>
  </table>